remote-theme: jekyll/minima

header_pages:
  - psychology.md


minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/stevwyman" }
    - { platform: twitter, user_url: "https://twitter.com/comwyca" }