remote_theme: jekyll/minima

title: My Notes
description: Some of my notes for quick reference
author.name: "Stev Wyman"

github_username: stevwyman

header_pages: 
  - web-dev.md
  - game_theory.md
  - psychology.md

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - web-dev.md
  - game_theory.md
  - psychology.md
  - gt_games.md
  - gt-representation.md
