remote_theme: jekyll/minima

header_pages: 
  - web-dev.md
  - game_theory.md
  - psychology.md

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - web-dev.md
  - game_theory.md
  - psychology.md
  - gt_games.md
  - gt-representation.md
