remote_theme: jekyll/minima

header_pages:
  - _pages/psychology.md

include:
  - _pages


minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/stevwyman" }
    - { platform: twitter, user_url: "https://twitter.com/comwyca" }