title: My Notes
description: Some of my notes for quick reference
author: "Stev Wyman"
remote_theme: jekyll/minima
github_username: stevwyman
header_pages: 
  - web-dev.md
  - game_theory.md
  - psychology.md

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - game_theory.md
  - gt_games.md
  - gt-representation.md
